apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-cosi-driver
  labels:
    app.kubernetes.io/name: sg-cosi-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sg-cosi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sg-cosi-driver
    spec:
      serviceAccountName: sg-cosi-driver
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: driver
          image: docker.io/scaleoutsean/sg-cosi-driver:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          args:
            - "--endpoint=/var/lib/cosi/cosi.sock"
          env:
            - name: DRIVER_NAME
              value: "sg.cosi.dev"
            - name: STORAGEGRID_S3_ENDPOINT
              value: "https://192.168.1.211:10443"
            - name: STORAGEGRID_ADMIN_ENDPOINT
              value: "https://192.168.1.211:9443"
            - name: STORAGEGRID_REGION
              value: "us-east-1"
            - name: AWS_S3_ADDRESSING_STYLE
              value: "path"
            - name: STORAGEGRID_INSECURE_SKIP_VERIFY
              value: "true"
            - name: TENANT_ACCOUNT_ID
              value: "72383031060298248956"
            - name: TENANT_GROUP_ID
              value: "a5e9cbcb-181b-4506-9551-fb1a7c52c820"
            - name: TENANT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: storagegrid-tenant-credentials
                  key: username
            - name: TENANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storagegrid-tenant-credentials
                  key: password
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/cosi

        - name: sidecar
          image: registry.k8s.io/sig-storage/objectstorage-sidecar:v0.2.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          args:
            - "--driver-addr=unix:///var/lib/cosi/cosi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/cosi

      volumes:
        - name: socket-dir
          emptyDir: {}
